### CONFIG SETTINGS FOR RASPLEX/OPENPHT TO PSEUDO CHANNEL REMOTE SCRIPT ###

# NAME OF THE PLEX CLIENT DEVICE THIS SCRIPT IS INSTALLED ON
client_name="RasPlex" 

# IP ADDRESS OF THE DEVICE THAT PSEUDO CHANNEL IS INSTALLED TO
controller_ip="192.168.1.100"

# FULL PATH LOCATION TO TEXT FILE THAT TRACKS THE BUTTONS PRESSED
leadButtonFileName = "/storage/rasplex-to-pseudo-channel-remote/leadbutton.txt" #change this value to match your file path

# MAXIMUM NUMBER OF DIGITS IN CHANNEL NUMBERS; THIS WILL INDICATE HOW MANY DIGITS WILL NEED TO BE ENTERED BEFORE EXECUTING
# (ONLY SUPPORTS VAULES OF 2 OR 3)
channelDigits = 2
